package model

data class TripDetailModel(
    val status: Boolean = false,
    val message: String = "",
    val `data`: Data = Data()
) {
    data class Data(
        val id: String = "",
        val booking_type: String = "",
        val rent_type: String = "",
        val booking_from: String = "",
        val company_id: String = "",
        val corporate_company_id: String = "",
        val company_vehicle_type_id: String = "",
        val fix_rate_id: String = "",
        val driver_id: String = "",
        val customer_id: String = "",
        val vehicle_type_id: String = "",
        val pickup_location: String = "",
        val dropoff_location: String = "",
        val pickup_lat: String = "",
        val pickup_lng: String = "",
        val dropoff_lat: String = "",
        val dropoff_lng: String = "",
        val status: String = "",
        val on_the_way: String = "",
        val pickup_date_time: String = "",
        val booking_time: String = "",
        val accept_time: String = "",
        val arrived_time: String = "",
        val pickup_time: String = "",
        val dropoff_time: String = "",
        val waiting_time: String = "",
        val waiting_time_charge: String = "",
        val payment_type: String = "",
        val is_changed_payment_type: String = "",
        val card_id: String = "",
        val pin: String = "",
        val payment_status: String = "",
        val reference_id: String = "",
        val jambopay_order_id: Any = Any(),
        val payment_response: String = "",
        val request_response: Any = Any(),
        val request_data: Any = Any(),
        val request_id: String = "",
        val promocode: String = "",
        val tips_status: String = "",
        val trip_duration: String = "",
        val distance: String = "",
        val tips: String = "",
        val distance_fare: String = "",
        val duration_fare: String = "",
        val base_fare: String = "",
        val booking_fee: String = "",
        val extra_charge: String = "",
        val sub_total: String = "",
        val discount: String = "",
        val saving_wallet_amount: String = "",
        val customer_saving_wallet_amount: String = "",
        val driver_wallet_percentage: String = "",
        val customer_saving_wallet_percentage: String = "",
        val grand_total: String = "",
        val total_equipment_price: String = "",
        val ambulance_package_id: String = "",
        val equipment_id: String = "",
        val booking_note: String = "",
        val tax: String = "",
        val driver_amount: String = "",
        val company_amount: String = "",
        val other_company_amount: String = "",
        val corporate_company_amount: String = "",
        val no_of_passenger: String = "",
        val cancellation_charge: String = "",
        val cancel_by: String = "",
        val cancele_reason: String = "",
        val cancel_time: String = "",
        val estimated_fare: String = "",
        val fare_increase_id: String = "",
        val fare_increase: String = "",
        val request_code: String = "",
        val cron_status: String = "",
        val request_by_cron: String = "",
        val payment_url: String = "",
        val is_corporate_driver: String = "",
        val corporate_driver_type: String = "",
        val vehicle_type_name: String = "",
        val customer_first_name: String = "",
        val customer_last_name: String = "",
        val vehicle_plate_number: String = "",
        val vehicle_model: String = "",
        val vehicle_name: String = "",
        val driver_first_name: String = "",
        val driver_last_name: String = "",
        val driver_profile_image: String = "",
        val driver_mobile_no: String = "",
        val rating: String = "",
        val ambulance_vehicle_name: String = "",
        val ambulance_plate_number: String = "",
        val total_time: Int = 0,
        val package_type: String = "",
        val booking_equipments: List<BookingEquipment> = listOf()
    ) {
        data class BookingEquipment(
            val name: String = ""
        )
    }
}